<?php

namespace App\Models;

use App\Trait\SelfReferenceTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class PagePost extends Model
{
    protected $guarded = [];
    protected $casts = [
        'meta' => 'array',
    ];
    use selfReferenceTrait;

    protected static function booted(): void
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::creating(function (PagePost $pagePost) {
            if (!$pagePost->slug){
                $pagePost->slug = Str::slug($pagePost->section_name);
            }
        });
        static::updating(function (PagePost $pagePost) {
            if ($pagePost->isDirty('section_name')) {
                $pagePost->slug = Str::slug($pagePost->section_name);
            }
        });
    }
}
